import { createSlice } from "@reduxjs/toolkit";

const mailSlice = createSlice({
  name: "mail", // Name of the slice
  initialState: {
    inboxData: [], // Initial state for inbox data
    outboxData: [], // Initial state for outbox data
    unread: 0, // Initial state for unread count
  },
  reducers: {
    // Reducer for updating inboxData
    inboxHandler(state, action) {
      state.inboxData = action.payload;
    },
    // Reducer for updating outboxData
    outboxHandler(state, action) {
      state.outboxData = action.payload;
    },
    // Reducer for updating unread count
    unreadHandler(state, action) {
      state.unread = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { inboxHandler, outboxHandler, unreadHandler } = mailSlice.actions;

// Export the reducer
export default mailSlice.reducer;
